name: test

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/bake-action@v4
        with:
          push: false
          set: |
              opaleye.cache-from=type=gha
              opaleye.cache-to=type=gha,mode=max
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
      - name: Load
        uses: docker/bake-action@v4
        with:
          push: false
          load: true
          set: |
              opaleye.cache-from=type=gha
              opaleye.cache-to=type=gha,mode=max
      - name: Build the stack
        run: docker compose up --exit-code-from opaleye
